import { Card, DiagnosisReport, ExecutionResult, CodexSessionUpdatePayload } from './types';
import { wekanApi } from './wekanApi';
import { githubSync } from './githubSync';
import { pmSyncManager } from './pmSyncManager';

export class CodexAcpClient {
  private isAvailable: boolean = false;

  constructor() {
    this.isAvailable = typeof window !== 'undefined' && !!window.electronAPI?.codexRunDiagnosis;
  }

  public async init(): Promise<{ success: boolean; error?: string }> {
    if (!window.electronAPI?.codexInit) {
      return { success: false, error: 'Codex ACP IPC not available in this environment' };
    }
    return await window.electronAPI.codexInit();
  }

  public async getStatus(): Promise<{ isReady: boolean; activeSessions: number; error?: string }> {
    if (!window.electronAPI?.codexGetStatus) {
      return { isReady: false, activeSessions: 0 };
    }
    return await window.electronAPI.codexGetStatus();
  }

  /**
   * Stage 2: Gathering Context & Diagnosis
   */
  public async runDiagnosis(
    card: Card,
    context: {
      boardId: string;
      boardTitle?: string;
      swimlaneTitle?: string;
      serverUrl?: string;
      token?: string;
    }
  ): Promise<{ success: boolean; report?: string; diagnosis?: DiagnosisReport; error?: string }> {
    if (!window.electronAPI?.codexRunDiagnosis) {
      return { success: false, error: 'Codex ACP IPC is not available' };
    }

    // 1. Read existing learnings
    let learnings = '';
    if (window.electronAPI?.readLearningsFile) {
      learnings = await window.electronAPI.readLearningsFile();
    }

    // 2. Dispatch diagnosis to Codex ACP
    const result = await window.electronAPI.codexRunDiagnosis({
      cardId: card._id,
      title: card.title,
      description: card.description || '',
      boardTitle: context.boardTitle,
      swimlaneTitle: context.swimlaneTitle,
      learnings,
    });

    if (!result.success || !result.diagnosis) {
      return {
        success: false,
        error: result.error || 'Failed to complete Codex diagnosis session',
      };
    }

    const diagnosis = result.diagnosis;

    // 3. Format structured card comment
    const commentMarkdown = `### 🔍 Codex Diagnosis Report

**Verdict:** \`${diagnosis.verdict.toUpperCase()}\`
**Suggested Severity:** \`${diagnosis.suggestedSeverity.toUpperCase()}\`

#### 📋 Reproduction & Verification
${diagnosis.reproSteps.length > 0 ? diagnosis.reproSteps.map(s => `- ${s}`).join('\n') : '- Codebase inspected; static verification applied.'}

#### 🛠️ Technical Findings & Recommendations
${diagnosis.details}

---
*Generated by Codex ACP Pipeline — Human review required before advancing to Execution.*`;

    // 4. Write comment back to Wekan card
    if (context.serverUrl && context.token && context.boardId) {
      try {
        await wekanApi.addComment(
          context.serverUrl,
          context.token,
          context.boardId,
          card._id,
          commentMarkdown
        );
      } catch (commentErr) {
        console.warn('[CodexAcpClient] Could not post diagnosis comment to card:', commentErr);
      }
    }

    // Broadcast to external PM tools (Jira, Linear, GitHub)
    try {
      await pmSyncManager.broadcastComment(card, commentMarkdown);
    } catch (_) {}

    return {
      success: true,
      report: commentMarkdown,
      diagnosis,
    };
  }

  /**
   * Stage 3: In Progress / Codex Execution
   */
  public async runExecution(
    card: Card,
    diagnosisReport: string,
    context: {
      boardId: string;
      serverUrl?: string;
      token?: string;
      githubRepo?: string;
      githubPat?: string;
    }
  ): Promise<ExecutionResult> {
    if (!window.electronAPI?.codexRunExecution) {
      return {
        success: false,
        branch: '',
        lintPassed: false,
        summary: '',
        error: 'Codex ACP execution IPC is not available',
      };
    }

    // 1. Read existing learnings
    let learnings = '';
    if (window.electronAPI?.readLearningsFile) {
      learnings = await window.electronAPI.readLearningsFile();
    }

    // 2. Dispatch execution to Codex ACP
    const execRes = await window.electronAPI.codexRunExecution({
      cardId: card._id,
      title: card.title,
      description: card.description || '',
      diagnosisReport,
      learnings,
    });

    if (!execRes.success) {
      return {
        success: false,
        branch: execRes.branch || '',
        filesChanged: execRes.filesChanged || [],
        lintPassed: execRes.lintPassed,
        summary: execRes.summary,
        error: execRes.error || 'Execution failed or deterministic quality gate did not pass',
      };
    }

    let prUrl: string | undefined;
    let prNumber: number | undefined;

    // 3. If GitHub PAT and Repo are configured, auto-open PR
    if (context.githubRepo && context.githubPat && execRes.branch) {
      try {
        const pr = await githubSync.createPullRequest(
          context.githubRepo,
          context.githubPat,
          {
            title: `[Pipeline] ${card.title}`,
            head: execRes.branch,
            base: 'main',
            body: `### Autonomous Codex PR for Card: ${card.title}

#### Implementation Summary
${execRes.summary}

#### Files Modified
${(execRes.filesChanged || []).map(f => `- \`${f}\``).join('\n')}

#### Quality Gate
- Deterministic checks (tsc / lint / tests): **PASSED**

---
*Auto-created by Lumora Codex ACP Pipeline*`,
          }
        );
        prUrl = pr.html_url;
        prNumber = pr.number;
      } catch (prErr: any) {
        console.warn('[CodexAcpClient] Failed to create GitHub PR:', prErr.message);
      }
    }

    // 4. Format completion comment
    const filesList = (execRes.filesChanged || []);
    const completionComment = `### 🚀 Codex Execution Complete

**Branch:** \`${execRes.branch}\`
**Quality Gate (tsc/lint/test):** \`PASSED\`
${prUrl ? `**Pull Request:** [PR #${prNumber} — ${prUrl}](${prUrl})` : '*Committed to local feature branch.*'}

#### 📝 Changes Implemented
${execRes.summary}

#### 📂 Files Modified
${filesList.length > 0 ? filesList.map(f => `- \`${f}\``).join('\n') : '- No additional file diffs recorded.'}

---
*Advancing card to Code Review & PR Verification for human signoff.*`;


    // 5. Write comment to Wekan card
    if (context.serverUrl && context.token && context.boardId) {
      try {
        await wekanApi.addComment(
          context.serverUrl,
          context.token,
          context.boardId,
          card._id,
          completionComment
        );
      } catch (commentErr) {
        console.warn('[CodexAcpClient] Could not post execution comment:', commentErr);
      }
    }

    // Broadcast to external PM tools (Jira, Linear, GitHub)
    try {
      await pmSyncManager.broadcastComment(card, completionComment);
    } catch (_) {}

    return {
      success: true,
      branch: execRes.branch,
      prUrl,
      prNumber,
      filesChanged: execRes.filesChanged,
      lintPassed: true,
      summary: execRes.summary,
    };
  }

  public cancelSession(cardId: string): boolean {
    if (window.electronAPI?.codexCancelSession) {
      window.electronAPI.codexCancelSession(cardId);
      return true;
    }
    return false;
  }

  public onUpdate(callback: (update: CodexSessionUpdatePayload) => void): () => void {
    if (window.electronAPI?.onCodexUpdate) {
      return window.electronAPI.onCodexUpdate(callback);
    }
    return () => {};
  }
}

export const codexAcpClient = new CodexAcpClient();
