import { describe, it, expect } from 'vitest';
import { parseAttachedFile } from '../src/renderer/lib/documentParser';
import { parseActionsFromText } from '../src/renderer/lib/aiService';

describe('DocumentParser & Multi-Task Ingestion Tests', () => {
  it('parses CSV spreadsheet files into markdown tables with row statistics', async () => {
    const csvContent = `Task ID,Title,Component,Status,Priority
TC-101,Fix login OAuth redirect loop,Auth,Open,High
TC-102,Implement dark mode theme switch,UI,In Progress,Medium
TC-103,Optimize database indexing for cards,Backend,Backlog,Critical`;

    const file = new File([csvContent], 'test_cases.csv', { type: 'text/csv' });
    const doc = await parseAttachedFile(file);

    expect(doc.type).toBe('spreadsheet');
    expect(doc.name).toBe('test_cases.csv');
    expect(doc.rowCount).toBe(3);
    expect(doc.parsedContent).toContain('| Task ID | Title | Component | Status | Priority |');
    expect(doc.parsedContent).toContain('| TC-101 | Fix login OAuth redirect loop | Auth | Open | High |');
    expect(doc.parsedContent).toContain('| TC-103 | Optimize database indexing for cards | Backend | Backlog | Critical |');
  });

  it('parses JSON data files into formatted text representation', async () => {
    const jsonContent = JSON.stringify({
      projectName: 'Kanso Alpha',
      milestones: [
        { id: 1, name: 'V1 Release', date: '2026-09-01' },
        { id: 2, name: 'Cloud Sync', date: '2026-10-15' },
      ],
    });

    const file = new File([jsonContent], 'roadmap.json', { type: 'application/json' });
    const doc = await parseAttachedFile(file);

    expect(doc.type).toBe('json');
    expect(doc.name).toBe('roadmap.json');
    expect(doc.parsedContent).toContain('"projectName": "Kanso Alpha"');
    expect(doc.parsedContent).toContain('"V1 Release"');
  });

  it('parses multi-card batch actions generated by AI from complex spreadsheets or vague prompts', () => {
    const aiResponseText = `I have parsed your testing spreadsheet and created 3 distinct Kanban cards across your workspace:

1. **Fix login OAuth redirect loop** (Auth subfolder → Reported Issues)
2. **Implement dark mode theme switch** (Frontend subfolder → In Progress)
3. **Optimize database indexing** (Backend subfolder → Backlog)

[ACTION:CREATE_CARD listId="list_issues" title="Fix login OAuth redirect loop" swimlaneId="sw_auth" description="Fix OAuth loop in callback handler" dueDays="3"]
[ACTION:CREATE_CARD listId="list_prog" title="Implement dark mode theme switch" swimlaneId="sw_ui" description="CSS custom properties theme engine" dueDays="7"]
[ACTION:CREATE_CARD listId="list_backlog" title="Optimize database indexing for cards" swimlaneId="sw_backend" description="Add compound index on boardId and listId" dueDays="14"]`;

    const { cleanText, actions } = parseActionsFromText(aiResponseText);

    expect(actions.length).toBe(3);
    expect(actions[0].type).toBe('CREATE_CARD');
    expect(actions[0].params.listId).toBe('list_issues');
    expect(actions[0].params.title).toBe('Fix login OAuth redirect loop');
    expect(actions[0].params.swimlaneId).toBe('sw_auth');
    expect(actions[0].params.dueDays).toBe('3');

    expect(actions[1].params.listId).toBe('list_prog');
    expect(actions[1].params.title).toBe('Implement dark mode theme switch');
    expect(actions[1].params.swimlaneId).toBe('sw_ui');

    expect(actions[2].params.listId).toBe('list_backlog');
    expect(actions[2].params.title).toBe('Optimize database indexing for cards');
    expect(actions[2].params.swimlaneId).toBe('sw_backend');

    expect(cleanText).not.toContain('[ACTION:');
    expect(cleanText).toContain('1. **Fix login OAuth redirect loop**');
  });
});
